### ISSUE TITLE
Binary distribution?

### ISSUE THREAD

**Issue by vladimirfx** [vorburger/osgi-services-di#1]
I've liked conceptual clearance of you lib. Actually we are trying to build something similar in our company.  How can I try your solution in one of my project?

**Comment by vorburger** [comment]
> I've liked conceptual clearance of you lib.

Thanks!

> Actually we are trying to build something similar in our company. 

Cool. If you like it, feel free to go ahead and fork it, compliant with the [EPL license](https://github.com/vorburger/osgi-services-di/blob/master/LICENSE).

> How can I try your solution in one of my project?

I'm not sure how you mean that; you can just locally build it (using ./gradlew), of coure.

FYI I'm not actively using this project myself, so I won't be providing a binary distribution.

**Comment by vladimirfx** [comment]
Thank you! I will try it and give you feedback.
